print("Bem Vindo a historia maluca!")
h= input("insira o nome da historia: ")
l= input("insira o nome de uma pessoa: ")
l1= input("insira um transporte: ")
l2= input("insira um parte do transporte: ")
l3= input("insira um animal ")
l4= input("insira um tipo de fruta: ")
l5= input("nome feminino ou masculino: ")
l6= input("insira um tipo de ferramenta: ")
l7= input("insira um lugar: ")
l8= input("insira nome do pai ")
l9= input("insira um move da casa: ")
l10 = input("insira o uma coisa:")

print("\n\n                   ",h)
print("Era uma vez {} que levava {} encanto andava de {} que estava voando quando os seus quatro {} furão, e sete {} foram ajudar. Quantas {} sobraram? Nenhuma,".format(l,l4,l1,l2,l3,l4))
print("quando {} viu sue(a) namora(o) no {} foi ajudar com {} e cair na {} em frente à casa onde morava. Quando {} chegou, sentiu muita emoção ao ver o {} na {} do seu avó.".format(l5,l10,l6,l7,l,l8,l9))
